version: "3"
services:
  apisix:
    image: apache/apisix:latest
    volumes:
      - ./apisix/config.yml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix/apisix.yml:/usr/local/apisix/conf/apisix.yaml:ro
    ports:
      - "9080:9080"
    environment:
      - GATEWAY_PORT=9080
  
  backend:
    image: nginx:1.19.0-alpine
    restart: always
    volumes:
      - ./upstream/backend.conf:/etc/nginx/nginx.conf
    ports:
      - "9081:80/tcp"
    environment:
      - NGINX_PORT=80